try{
'use strict';var l,m=this,aa=function(a){a.M=function(){return a.S?a.S:a.S=new a}},ba=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&
"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},n=function(a){return"array"==ba(a)},ca=function(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length},p=function(a){return"string"==typeof a},da=function(a){return"function"==ba(a)},ea=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},fa="closure_uid_"+(1E9*Math.random()>>>0),
ga=0,ha=function(a,b,c){return a.call.apply(a.bind,arguments)},ia=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},r=function(a,b,c){r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ha:ia;return r.apply(null,arguments)},ja=function(a,b){var c=
Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},t=Date.now||function(){return+new Date},u=function(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.w=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};
var v=function(){this.h=this.h;this.g=this.g};v.prototype.h=!1;v.prototype.P=function(){this.h||(this.h=!0,this.C())};var ka=function(a,b){a.h?b.call(void 0):(a.g||(a.g=[]),a.g.push(b))};v.prototype.C=function(){if(this.g)for(;this.g.length;)this.g.shift()()};var la=function(a){a&&"function"==typeof a.P&&a.P()};
var w=function(a,b){this.type=a;this.a=this.target=b;this.U=!0};w.prototype.g=function(){this.U=!1};var ma=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},ua=function(a){if(!na.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(oa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(pa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(qa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ra,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(sa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(ta,"&#0;"));return a},oa=/&/g,pa=/</g,qa=/>/g,ra=/"/g,sa=/'/g,ta=/\x00/g,na=/[\x00&<>"']/, x=function(a){return null==a?"":String(a)},va=function(a,b){return a<b?-1:a>b?1:0};
var wa=function(a){w.call(this,a);this.h=0;this.c=null;this.m=this.o="";this.s=0;this.i=""};u(wa,w);var xa=function(a,b,c,d,e){var f=new wa("clip_changed");f.c=a;f.h=b;f.o=c;f.m=d;e&&(f.s=e.i,f.i=e.B());return f};wa.prototype.F=function(){return x(this.c&&this.c.B()||null)};
var z=Array.prototype,ya=z.indexOf?function(a,b,c){return z.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(p(a))return p(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},za=z.forEach?function(a,b,c){z.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=p(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Aa=z.map?function(a,b,c){return z.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=p(a)?a.split(""): a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e},Ba=function(a){return z.concat.apply(z,arguments)},Ca=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Da=function(a,b){return a>b?1:a<b?-1:0};
var Ea=m.JSON.stringify;var Fa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Ga=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Ha="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Ia=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ha.length;f++)c=Ha[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},Ja=function(a){var b=arguments.length;if(1==b&&n(arguments[0]))return Ja.apply(null, arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};
var A=function(){},B=function(a,b,c,d){a.a=null;b||(b=[]);a.m=void 0;a.i=-1;a.c=b;a:{if(a.c.length){b=a.c.length-1;var e=a.c[b];if(e&&"object"==typeof e&&!n(e)){a.h=b-a.i;a.g=e;break a}}-1<c?(a.h=c,a.g=null):a.h=Number.MAX_VALUE}if(d)for(c=0;c<d.length;c++)b=d[c],b<a.h?(b+=a.i,a.c[b]=a.c[b]||Ka):a.g[b]=a.g[b]||Ka},Ka=[],C=function(a,b){if(b<a.h){var c=b+a.i,d=a.c[c];return d===Ka?a.c[c]=[]:d}d=a.g[b];return d===Ka?a.g[b]=[]:d},D=function(a,b,c){b<a.h?a.c[b+a.i]=c:a.g[b]=c},E=function(a,b,c){a.a||
(a.a={});if(!a.a[c]){var d=C(a,c);d&&(a.a[c]=new b(d))}return a.a[c]},F=function(a,b,c){a.a||(a.a={});var d=c?c.c:c;a.a[b]=c;D(a,b,d)};A.prototype.l=function(){return m.JSON&&m.JSON.stringify?m.JSON.stringify(this.c):Ea(this.c)};A.prototype.toString=function(){return this.c.toString()};
var Ma=function(a){var b=La;if(a.g){a.a||(a.a={});var c=b.c;if(b.g){if(b.a)return a.a[c]||(a.a[c]=Aa(a.g[c]||[],function(a){return new b.a(a)})),a.a[c]}else if(b.a)return!a.a[c]&&a.g[c]&&(a.a[c]=new b.a(a.g[c])),a.a[c];return a.g[c]}},Na=function(a){var b;if(n(a)){for(var c=Array(a.length),d=0;d<a.length;d++)null!=(b=a[d])&&(c[d]="object"==typeof b?Na(b):b);return c}c={};for(d in a)null!=(b=a[d])&&(c[d]="object"==typeof b?Na(b):b);return c};
var Pa=function(a){B(this,a,-1,Oa)};u(Pa,A);var Oa=[3];Pa.prototype.getTitle=function(){return C(this,2)};Pa.prototype.setTitle=function(a){D(this,2,a)};var Qa=function(a){this.a=a||new Pa};Qa.prototype.setTitle=function(a){this.a.setTitle(a)};Qa.prototype.l=function(){return this.a.l()};var Ra=function(a){B(this,a,-1,null)};u(Ra,A);var H=function(a){return E(a,G,2)},G=function(a){B(this,a,-1,null)};u(G,A);var Sa=function(a){return C(a,1)};var Ta=function(a){B(this,a,-1,null)};u(Ta,A);Ta.prototype.B=function(){return C(this,1)};var Ua=function(a){B(this,a,-1,null)};u(Ua,A);Ua.prototype.getTitle=function(){return C(this,1)};Ua.prototype.setTitle=function(a){D(this,1,a)};var Va=function(a){B(this,a,-1,null)};u(Va,A);var Wa=function(a){B(this,a,-1,null)};u(Wa,A);var Ya=function(a){B(this,a,22,Xa)};u(Ya,A);var Xa=[3];Ya.prototype.F=function(){return E(this,Ta,1)};var Za=function(a){B(this,a,-1,null)};u(Za,A);var $a=function(a){this.a=a||new Za};$a.prototype.l=function(){return this.a.l()};var ab;a:{var bb=m.navigator;if(bb){var cb=bb.userAgent;if(cb){ab=cb;break a}}ab=""}var I=function(a){return-1!=ab.indexOf(a)};var db=function(){return I("Opera")||I("OPR")},eb=function(){return I("Edge")||I("Trident")||I("MSIE")},fb=function(){return(I("Chrome")||I("CriOS"))&&!db()&&!eb()};var J=function(){return I("Edge")};var gb=db(),K=eb(),hb=I("Gecko")&&!(-1!=ab.toLowerCase().indexOf("webkit")&&!J())&&!(I("Trident")||I("MSIE"))&&!J(),ib=-1!=ab.toLowerCase().indexOf("webkit")&&!J(),jb=function(){var a=ab;if(hb)return/rv\:([^\);]+)(\)|;)/.exec(a);if(K&&J())return/Edge\/([\d\.]+)/.exec(a);if(K)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(ib)return/WebKit\/(\S+)/.exec(a)},kb=function(){var a=m.document;return a?a.documentMode:void 0},lb=function(){if(gb&&m.opera){var a=m.opera.version;return da(a)?a():a}var a=
"",b=jb();b&&(a=b?b[1]:"");return K&&!J()&&(b=kb(),b>parseFloat(a))?String(b):a}(),mb={},L=function(a){var b;if(!(b=mb[a])){b=0;for(var c=ma(String(lb)).split("."),d=ma(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",k=/(\d*)(\D*)/g,y=/(\d*)(\D*)/g;do{var q=k.exec(g)||["","",""],T=y.exec(h)||["","",""];if(0==q[0].length&&0==T[0].length)break;b=va(0==q[1].length?0:parseInt(q[1],10),0==T[1].length?0:parseInt(T[1],10))||va(0==q[2].length,0==T[2].length)|| va(q[2],T[2])}while(0==b)}b=mb[a]=0<=b}return b},nb=m.document,ob=kb(),pb=!nb||!K||!ob&&J()?void 0:ob||("CSS1Compat"==nb.compatMode?parseInt(lb,10):5);
var qb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,sb=function(a){if(rb){rb=!1;var b=m.location;if(b){var c=b.href;if(c&&(c=(c=sb(c)[3]||null)?decodeURI(c):c)&&c!=b.hostname)throw rb=!0,Error();}}return a.match(qb)},rb=ib,tb=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?decodeURIComponent(g.replace(/\+/g," ")):"")}};
var ub="StopIteration"in m?m.StopIteration:{message:"StopIteration",stack:""},vb=function(){};vb.prototype.a=function(){throw ub;};vb.prototype.L=function(){return this};var M=function(a,b){this.c={};this.a=[];this.h=this.g=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){if(a instanceof M)d=a.G(),c=a.v();else{var c=[],e=0;for(d in a)c[e++]=d;d=c;c=Ga(a)}for(e=0;e<d.length;e++)this.set(d[e],c[e])}};M.prototype.v=function(){wb(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.c[this.a[b]]);return a};M.prototype.G=function(){wb(this);return this.a.concat()};
M.prototype.remove=function(a){return N(this.c,a)?(delete this.c[a],this.g--,this.h++,this.a.length>2*this.g&&wb(this),!0):!1};var wb=function(a){if(a.g!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];N(a.c,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.g!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],N(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};l=M.prototype;l.get=function(a,b){return N(this.c,a)?this.c[a]:b};
l.set=function(a,b){N(this.c,a)||(this.g++,this.a.push(a),this.h++);this.c[a]=b};l.forEach=function(a,b){for(var c=this.G(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};l.clone=function(){return new M(this)};l.L=function(a){wb(this);var b=0,c=this.h,d=this,e=new vb;e.a=function(){if(c!=d.h)throw Error("The map has changed since the iterator was created");if(b>=d.a.length)throw ub;var e=d.a[b++];return a?e:d.c[e]};return e}; var N=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var xb=function(a){if("function"==typeof a.v)return a.v();if(p(a))return a.split("");if(ca(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ga(a)};var O=function(a,b){this.g=this.s=this.c="";this.o=null;this.i=this.m="";this.a=!1;var c;a instanceof O?(this.a=void 0!==b?b:a.a,yb(this,a.c),this.s=a.s,this.g=a.g,zb(this,a.o),this.m=a.m,Ab(this,a.h.clone()),this.i=a.i):a&&(c=sb(String(a)))?(this.a=!!b,yb(this,c[1]||"",!0),this.s=Bb(c[2]||""),this.g=Bb(c[3]||"",!0),zb(this,c[4]),this.m=Bb(c[5]||"",!0),Ab(this,c[6]||"",!0),this.i=Bb(c[7]||"")):(this.a=!!b,this.h=new Cb(null,0,this.a))};
O.prototype.toString=function(){var a=[],b=this.c;b&&a.push(Db(b,Eb,!0),":");if(b=this.g){a.push("//");var c=this.s;c&&a.push(Db(c,Eb,!0),"@");a.push(encodeURIComponent(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.o;null!=b&&a.push(":",String(b))}if(b=this.m)this.g&&"/"!=b.charAt(0)&&a.push("/"),a.push(Db(b,"/"==b.charAt(0)?Fb:Gb,!0));(b=this.h.toString())&&a.push("?",b);(b=this.i)&&a.push("#",Db(b,Hb));return a.join("")};O.prototype.clone=function(){return new O(this)};
var yb=function(a,b,c){a.c=c?Bb(b,!0):b;a.c&&(a.c=a.c.replace(/:$/,""))},zb=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.o=b}else a.o=null},Ab=function(a,b,c){b instanceof Cb?(a.h=b,Ib(a.h,a.a)):(c||(b=Db(b,Jb)),a.h=new Cb(b,0,a.a))},Kb=function(a){a instanceof O?a.clone():new O(a,void 0)},Bb=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},Db=function(a,b,c){return p(a)?(a=encodeURI(a).replace(b,Lb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,
"%$1")),a):null},Lb=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Eb=/[#\/\?@]/g,Gb=/[\#\?:]/g,Fb=/[\#\?]/g,Jb=/[\#\?@]/g,Hb=/#/g,Cb=function(a,b,c){this.g=this.a=null;this.c=a||null;this.h=!!c},P=function(a){a.a||(a.a=new M,a.g=0,a.c&&tb(a.c,function(b,c){var d=decodeURIComponent(b.replace(/\+/g," "));P(a);a.c=null;var d=Mb(a,d),e=a.a.get(d);e||a.a.set(d,e=[]);e.push(c);a.g++}))};
Cb.prototype.remove=function(a){P(this);a=Mb(this,a);return N(this.a.c,a)?(this.c=null,this.g-=this.a.get(a).length,this.a.remove(a)):!1};var Nb=function(a,b){P(a);b=Mb(a,b);return N(a.a.c,b)};l=Cb.prototype;l.G=function(){P(this);for(var a=this.a.v(),b=this.a.G(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};l.v=function(a){P(this);var b=[];if(p(a))Nb(this,a)&&(b=Ba(b,this.a.get(Mb(this,a))));else{a=this.a.v();for(var c=0;c<a.length;c++)b=Ba(b,a[c])}return b};
l.set=function(a,b){P(this);this.c=null;a=Mb(this,a);Nb(this,a)&&(this.g-=this.a.get(a).length);this.a.set(a,[b]);this.g++;return this};l.get=function(a,b){var c=a?this.v(a):[];return 0<c.length?String(c[0]):b};l.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.G(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.v(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}return this.c=a.join("&")};
l.clone=function(){var a=new Cb;a.c=this.c;this.a&&(a.a=this.a.clone(),a.g=this.g);return a};var Mb=function(a,b){var c=String(b);a.h&&(c=c.toLowerCase());return c},Ib=function(a,b){b&&!a.h&&(P(a),a.c=null,a.a.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),this.remove(e),0<a.length&&(this.c=null,this.a.set(Mb(this,e),Ca(a)),this.g+=a.length))},a));a.h=b};
var Ob=function(a){this.a=a||new Ua;a=C(this.a,3);D(this.a,3,a)};Ob.prototype.getTitle=function(){return x(this.a.getTitle())};Ob.prototype.setTitle=function(a){this.a.setTitle(a)};Ob.prototype.l=function(){return this.a.l()};Ja("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));var Pb=function(){this.c="";this.a=null},Qb=function(a){var b=new Pb;b.c=a;b.a=0};Qb("<!DOCTYPE html>");Qb("");var Sb=function(a){this.a=new M;if(a){a=xb(a);for(var b=a.length,c=0;c<b;c++){var d=a[c];this.a.set(Rb(d),d)}}},Rb=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[fa]||(a[fa]=++ga)):b.substr(0,1)+a};l=Sb.prototype;l.removeAll=function(a){a=xb(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};l.remove=function(a){return this.a.remove(Rb(a))};l.v=function(){return this.a.v()};l.clone=function(){return new Sb(this)};l.L=function(){return this.a.L(!1)};
var Ub=function(a,b,c,d,e){"number"==typeof e||Tb++;this.g=d||t();this.h=a;this.i=b;this.c=c;delete this.a};Ub.prototype.a=null;var Tb=0;Ub.prototype.getMessage=function(){return this.i};var Vb=function(a){this.h=a;this.c=this.g=this.a=null},Wb=function(a,b){this.name=a;this.value=b};Wb.prototype.toString=function(){return this.name};var Xb=new Wb("SHOUT",1200),Yb=new Wb("SEVERE",1E3),Zb=new Wb("WARNING",900),$b=new Wb("INFO",800),ac=new Wb("CONFIG",700);Vb.prototype.getChildren=function(){this.c||(this.c={});return this.c};var bc=function(a){return a.g?a.g:a.a?bc(a.a):null};
Vb.prototype.log=function(a,b,c){if(a.value>=bc(this).value)for(da(b)&&(b=b()),a=new Ub(a,String(b),this.h),c&&(a.a=c),c="log:"+a.getMessage(),m.console&&(m.console.timeStamp?m.console.timeStamp(c):m.console.markTimeline&&m.console.markTimeline(c)),m.msWriteProfilerMark&&m.msWriteProfilerMark(c),c=this;c;)c=c.a}; var cc={},dc=null,ec=function(){dc||(dc=new Vb(""),cc[""]=dc,dc.g=ac)},fc=function(a){ec();var b;if(!(b=cc[a])){b=new Vb(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=fc(a.substr(0,c));c.getChildren()[d]=b;b.a=c;cc[a]=b}return b};
!I("Android")||fb()||I("Firefox")||db();fb();fc("gws.collections.models.IndexedClips");fc("gws.collections.models.IndexedFolios");var gc=function(){};aa(gc);var hc={0:"c_",1:"f_",2:"d_",3:"g_",4:"lc_",5:"lf_"},ic=function(a){return hc[a]+(839808*a+Math.floor(839808*Math.random())).toString(36)+t().toString(36)};var jc=function(a,b,c){w.call(this,c||"TRANSACTION_COMMIT");this.i=a||0;(a=b)||(gc.M(),a=ic(2));this.h=a;this.c=[];this.m=[]};u(jc,w);var lc=function(a,b,c){a.c.push(b);a.m.push(c);kc(c,b)};jc.prototype.B=function(){return this.h};var mc=!K||K&&(J()||9<=pb),nc=K&&!L("9");!ib||L("528");hb&&L("1.9b")||K&&L("8")||gb&&L("9.5")||ib&&L("528");hb&&!L("8")||K&&L("9");var oc=function(a){oc[" "](a);return a};oc[" "]=function(){};var pc=function(a,b){w.call(this,a?a.type:"");this.c=this.state=this.a=this.target=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;if(c&&hb)try{oc(c.nodeName)}catch(d){}this.state=a.state;this.c=a;a.defaultPrevented&&this.g()}};u(pc,w);pc.prototype.g=function(){pc.H.g.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,nc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var qc="closure_listenable_"+(1E6*Math.random()|0),rc=0;var sc=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.J=!!d;this.K=e;this.R=++rc;this.removed=this.I=!1},tc=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.K=null};var uc=function(a){this.src=a;this.a={};this.c=0},wc=function(a,b,c,d,e){var f=b.toString();b=a.a[f];b||(b=a.a[f]=[],a.c++);var g=vc(b,c,d,e);-1<g?(a=b[g],a.I=!1):(a=new sc(c,a.src,f,!!d,e),a.I=!1,b.push(a));return a};uc.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=vc(e,b,c,d);return-1<b?(tc(e[b]),z.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.c--),!0):!1};
var xc=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=a.a[c],e=ya(d,b),f;(f=0<=e)&&z.splice.call(d,e,1);f&&(tc(b),0==a.a[c].length&&(delete a.a[c],a.c--));return f};uc.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,tc(d[e]);delete this.a[c];this.c--}return b}; var yc=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=vc(a,c,d,e));return-1<b?a[b]:null},vc=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.J==!!c&&f.K==d)return e}return-1};
var zc="closure_lm_"+(1E6*Math.random()|0),Ac={},Bc=0,Cc=function(a,b,c,d,e){if(n(b)){for(var f=0;f<b.length;f++)Cc(a,b[f],c,d,e);return null}c=Dc(c);if(a&&a[qc])a=a.listen(b,c,d,e);else{if(!b)throw Error("Invalid event type");var f=!!d,g=Ec(a);g||(a[zc]=g=new uc(a));c=wc(g,b,c,d,e);c.proxy||(d=Fc(),c.proxy=d,d.src=a,d.listener=c,a.addEventListener?a.addEventListener(b.toString(),d,f):a.attachEvent(Gc(b.toString()),d),Bc++);a=c}return a},Fc=function(){var a=Hc,b=mc?function(c){return a.call(b.src,
b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},Ic=function(a,b,c,d,e){if(n(b))for(var f=0;f<b.length;f++)Ic(a,b[f],c,d,e);else c=Dc(c),a&&a[qc]?a.unlisten(b,c,d,e):a&&(a=Ec(a))&&(b=yc(a,b,c,!!d,e))&&Jc(b)},Jc=function(a){if("number"==typeof a||!a||a.removed)return!1;var b=a.src;if(b&&b[qc])return xc(b.A,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.J):b.detachEvent&&b.detachEvent(Gc(c),d);Bc--;(c=Ec(b))?(xc(c,a),0==c.c&&(c.src=null,
b[zc]=null)):tc(a);return!0},Gc=function(a){return a in Ac?Ac[a]:Ac[a]="on"+a},Lc=function(a,b,c,d){var e=!0;if(a=Ec(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.J==c&&!f.removed&&(f=Kc(f,d),e=e&&!1!==f)}return e},Kc=function(a,b){var c=a.listener,d=a.K||a.src;a.I&&Jc(a);return c.call(d,b)},Hc=function(a,b){if(a.removed)return!0;if(!mc){var c;if(!(c=b))a:{c=["window","event"];for(var d=m,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new pc(e,this);
d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,h=e.length-1;0<=h;h--){c.a=e[h];var k=Lc(e[h],f,!0,c),d=d&&k}for(h=0;h<e.length;h++)c.a=e[h],k=Lc(e[h],f,!1,c),d=d&&k}return d}return Kc(a,new pc(b,this))},Ec=function(a){a=a[zc];return a instanceof uc?a:null},Mc="__closure_events_fn_"+(1E9*Math.random()>>>0),Dc=function(a){if(da(a))return a; a[Mc]||(a[Mc]=function(b){return a.handleEvent(b)});return a[Mc]};
var Q=function(){v.call(this);this.A=new uc(this);this.X=this;this.m=null};u(Q,v);Q.prototype[qc]=!0;Q.prototype.removeEventListener=function(a,b,c,d){Ic(this,a,b,c,d)};
var kc=function(a,b){var c,d=a.m;if(d)for(c=[];d;d=d.m)c.push(d);var d=a.X,e=b,f=e.type||e;if(p(e))e=new w(e,d);else if(e instanceof w)e.target=e.target||d;else{var g=e,e=new w(f,d);Ia(e,g)}var g=!0,h;if(c)for(var k=c.length-1;0<=k;k--)h=e.a=c[k],g=Nc(h,f,!0,e)&&g;h=e.a=d;g=Nc(h,f,!0,e)&&g;g=Nc(h,f,!1,e)&&g;if(c)for(k=0;k<c.length;k++)h=e.a=c[k],g=Nc(h,f,!1,e)&&g};Q.prototype.C=function(){Q.H.C.call(this);this.A&&this.A.removeAll(void 0);this.m=null};
Q.prototype.listen=function(a,b,c,d){return wc(this.A,String(a),b,c,d)};Q.prototype.unlisten=function(a,b,c,d){return this.A.remove(String(a),b,c,d)};var Nc=function(a,b,c,d){b=a.A.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.removed&&g.J==c){var h=g.listener,k=g.K||g.src;g.I&&xc(a.A,g);e=!1!==h.call(k,d)&&e}}return e&&0!=d.U};
var Oc=function(){Q.call(this)};u(Oc,Q);var Pc=function(a){Q.call(this);this.a=a};u(Pc,Oc);Pc.prototype.B=function(){return this.a.F()?x(this.a.F().B()):""};Pc.prototype.l=function(){return this.a.l()};var Qc=function(a){v.call(this);this.c=a;this.a={}};u(Qc,v);var Rc=[];l=Qc.prototype;l.listen=function(a,b,c,d){n(b)||(b&&(Rc[0]=b.toString()),b=Rc);for(var e=0;e<b.length;e++){var f=Cc(a,b[e],c||this.handleEvent,d||!1,this.c||this);if(!f)break;this.a[f.R]=f}return this};
l.unlisten=function(a,b,c,d,e){if(n(b))for(var f=0;f<b.length;f++)this.unlisten(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.c||this,c=Dc(c),d=!!d,b=a&&a[qc]?yc(a.A,String(b),c,d,e):a?(a=Ec(a))?yc(a,b,c,d,e):null:null,b&&(Jc(b),delete this.a[b.R]);return this};l.removeAll=function(){Fa(this.a,Jc);this.a={}};l.C=function(){Qc.H.C.call(this);this.removeAll()};l.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};
var Tc=function(a){this.a=a||new Ra;if(!H(this.a)){a=this.a;var b=new G;F(a,2,b)}E(this.a,G,3)||(a=this.a,b=new G,F(a,3,b));this.c=new O(x(Sa(H(this.a))));new O(Sc(this))},Sc=function(a){return x(Sa(E(a.a,G,3))).replace(/^\/\//,"https://")};Tc.prototype.l=function(){return this.a.l()};
var Uc=function(a){this.a=a||new Va};Uc.prototype.l=function(){return this.a.l()};var Vc=function(a){this.a=a||new Wa};Vc.prototype.l=function(){return this.a.l()};var Wc=function(a){B(this,a,-1,null)};u(Wc,A);var La=new function(){this.c=71309500;this.a=Wc;this.g=0}(function(a,b){var c,d=C(b,1),e=C(b,2),f;if(f=c=b.getLocation())f={latitude:C(c,1),longitude:C(c,2)},a&&(f.V=c);c={Y:d,Z:e,location:f};a&&(c.V=b);return c});Wc.prototype.getLocation=function(){return E(this,Xc,3)};var Xc=function(a){B(this,a,-1,null)};u(Xc,A);
var Yc=!K||K&&(J()||9<=pb);!hb&&!K||K&&K&&(J()||9<=pb)||hb&&L("1.9.1");K&&L("9");var $c=function(a,b){Fa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Zc?a.setAttribute(Zc[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},Zc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},bd=function(a,b,c){var d=arguments,e=document,
f=d[0],g=d[1];if(!Yc&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',ua(g.name),'"');if(g.type){f.push(' type="',ua(g.type),'"');var h={};Ia(h,g);delete h.type;g=h}f.push(">");f=f.join("")}f=e.createElement(f);g&&(p(g)?f.className=g:n(g)?f.className=g.join(" "):$c(f,g));2<d.length&&ad(e,f,d);return f},ad=function(a,b,c){function d(c){c&&b.appendChild(p(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!ca(f)||ea(f)&&0<f.nodeType?d(f):za(cd(f)?Ca(f):f,d)}},cd=function(a){if(a&& "number"==typeof a.length){if(ea(a))return"function"==typeof a.item||"string"==typeof a.item;if(da(a))return"function"==typeof a.item}return!1};
var S=function(a){Pc.call(this,a||new Ya);this.c=dd(this);this.i=R(this);this.s=ed(this);a=this.a;a.a||(a.a={});if(!a.a[3]){for(var b=C(a,3),c=[],d=0;d<b.length;d++)c[d]=new Za(b[d]);a.a[3]=c}b=a.a[3];b==Ka&&(b=a.a[3]=[]);a=b;for(b=0;b<a.length;b++)c=new $a(a[b]),E(c.a,Ta,1).B();a=E(this.a,Wa,10);!this.o&&a&&(this.o=new Vc(a));this.o=this.o||null;a=E(this.a,Va,13);!this.D&&a&&(this.D=new Uc(a));this.D=this.D||null;new Sb;this.B()||(gc.M(),a=ic(0),this.a.F()||(b=new Ta,F(this.a,1,b)),b=this.a.F(),
D(b,1,a))};u(S,Pc);fc("gws.collections.models.ClipModel");S.prototype.clone=function(){var a;a=this.a;a=new a.constructor(Na(a.c));return new S(a)};var dd=function(a){var b=E(a.a,Ra,5);!a.c&&b&&(a.c=new Tc(b));if(!a.c&&3==C(a.a,4)){var b=ed(a),b=x(C(b.a,1)).replace(/\//g,"-"),b="https://www.gstatic.com/vd/kp/%s/en/1/image.jpg".replace("%s",b),c=bd("img");c.src=b;c.onload=r(a.O,a,c)}return a.c||null};
S.prototype.O=function(a){var b=new Tc,c=a.src,d=E(b.a,G,3);D(d,1,c);new O(Sc(b));c=a.naturalWidth;a=a.naturalHeight;d=E(b.a,G,3);D(d,2,c);c=E(b.a,G,3);D(c,3,a);var c=(a=new jc(3))||new jc,d=this.c&&this.c.l(),e=b.l();d!=e&&(this.c=b,F(this.a,5,b.a),b=t(),D(this.a,8,b),b=xa(this,203,d||"",e,c),lc(c,b,this),c!=a&&0<c.c.length&&kc(this,c))};var ed=function(a){var b=E(a.a,Pa,9);!a.s&&b&&(a.s=new Qa(b));return a.s||null},R=function(a){var b=E(a.a,Ua,6);!a.i&&b&&(a.i=new Ob(b));return a.i||null};
S.prototype.getTitle=function(){return R(this)?R(this).getTitle().toString():""};S.prototype.setTitle=function(a,b){var c=b||new jc;if(R(this).getTitle()==a)return!1;var d=R(this).l(),e=R(this);e.setTitle(a);var f=t();D(this.a,8,f);d=xa(this,204,d,e.l(),c);lc(c,d,this);c!=b&&0<c.c.length&&kc(this,c);return!0};var fd=function(a,b){var c=new jc,d=C(a.a,4);C(a.a,4)!=b&&(D(a.a,4,b),d=xa(a,206,""+d,""+b,c),lc(c,d,a),void 0!=c&&0<c.c.length&&kc(a,c))}; S.prototype.toString=function(){return"ClipModel:"+this.B()};S.prototype.getLocation=function(){var a=Ma(this.a);return a&&(a=a.getLocation())?x(C(a,1).toFixed(4)+","+C(a,2).toFixed(4)):""};
var gd=function(a){v.call(this);this.i=a;this.a={};this.c={}};u(gd,v);gd.prototype.C=function(){this.unlisten();gd.H.C.call(this)};gd.prototype.listen=function(a,b){var c=r(b,this.i);a.addListener(c);var d=a[fa]||(a[fa]=++ga);d in this.a?this.c[d].a.set(Rb(c),c):(this.a[d]=a,this.c[d]=new Sb([c]));return this}; gd.prototype.unlisten=function(a){if(a){var b=a[fa]||(a[fa]=++ga);if(b in this.a){var c=this.c[b].v();za(c,a.removeListener,a);delete this.c[b];delete this.a[b]}}else Fa(this.a,this.unlisten,this)};
var hd=function(){Q.call(this);this.O=new Qc(this);ka(this,ja(la,this.O))};u(hd,Q);hd.prototype.c=function(a){this.m=a};var id=function(a,b){this.width=a;this.height=b},jd=function(a){return a.width*a.height};var U=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.w=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}},kd={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},ld={IMG:" ",BR:"\n"},md=/&([^;\s<&]+);?/g,V=function(a,b){var c=nd(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""},pd=function(a){if("none"!=
V(a,"display"))return od(a);var b=a.style,c=b.display,d=b.visibility,e=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=od(a);b.display=c;b.position=e;b.visibility=d;return a},od=function(a){var b=a.offsetWidth,c=a.offsetHeight;return void 0===b||!b&&!c?(a=a.getBoundingClientRect(),new id(a.right-a.left,a.bottom-a.top)):new id(b,c)},nd=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document},qd=function(a){if(a.parentElement)return a.parentElement;a=a.parentNode;
return"object"==typeof a&&1==a.nodeType?a:null},sd=function(a){var b=[];rd(a,b);a=b.join("");a=a.replace(/ +/g," ");" "!=a&&(a=a.replace(/^\s*/,""));return a},rd=function(a,b){if(!(a.nodeName in kd))if(3==a.nodeType)b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,""));else if(a.nodeName in ld)b.push(ld[a.nodeName]);else for(var c=a.firstChild;c;)rd(c,b),c=c.nextSibling},td=function(a){if(-1==a.indexOf("&"))return a;var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c;c=document.createElement("div");
return a.replace(md,function(a,e){var f=b[a];if(f)return f;if("#"==e.charAt(0)){var g=Number("0"+e.substr(1));isNaN(g)||(f=String.fromCharCode(g))}f||(c.innerHTML=a+" ",f=c.firstChild.nodeValue.slice(0,-1));return b[a]=f})},ud=function(a){return a&&5<=a.length?"d"==a.charAt(0)&&"a"==a.charAt(1)&&"t"==a.charAt(2)&&"a"==a.charAt(3)&&":"==a.charAt(4):!1};
var vd=function(){this.a=["ad","advertisement","ads","sponsor","sponsored"]};vd.prototype.filter=function(a){for(;a;){for(var b=a.classList,c=0;c<b.length;++c)for(var d=b[c].split(/\W+/),e=0;e<d.length;++e)if(0<=this.a.indexOf(d[e].toLowerCase()))return!1;a=qd(a)}return!0};
var wd=function(a){this.c=a},xd=function(a,b){return a==b?0:a.c-b.c};var W=function(){this.h=[]};W.prototype.filter=function(a){for(var b=0;b<this.h.length;++b)if(!this.h[b].filter(a))return!1;return!0};var yd=function(a,b){var c=a.a(b);if(0==c.length)return null;for(var d=c[0],e=1;e<c.length;++e){var f=c[e];f.c>d.c&&(d=f)}return d};W.prototype.a=function(a){return X(this,a.getElementsByTagName("*"))};var X=function(a,b,c){for(var d=[],e=b.length,f=0;f<e;++f){var g=a.c(b[f],c);g&&d.push(g)}return d};W.prototype.c=function(){return null};
var Y=function(a,b,c,d){Y.w(this,"constructor",a);this.a=b;this.g=c;this.h=d};U(Y,wd);var zd=function(){};zd.prototype.filter=function(a){for(;a;){if("none"==V(a,"display"))return!1;var b=pd(a);if("hidden"==V(a,"overflow")&&0==jd(b)||"hidden"==V(a,"visibility"))return!1;a=qd(a)}return!0};var Ad=function(){Ad.w(this,"constructor");this.h.push(new vd);this.h.push(new zd);this.g=document.createElement("a")};U(Ad,W);var Bd={".gif":.5},Cd=function(){this.T=0;this.N={}};Ad.prototype.a=function(a){return X(this,a.getElementsByTagName("*"),new Cd)};
Ad.prototype.c=function(a,b){var c=null;switch(a.tagName.toLowerCase()){case "meta":c=Dd(this,a,1,"property","og:image","content")||Dd(this,a,.9,"name","msapplication-tileimage","content")||Dd(this,a,.8,"name","twitter:image","content")||Ed(a);break;case "link":c=Dd(this,a,.7,"rel","apple-touch-icon","href")||Dd(this,a,.6,"rel","image_src","href")||Ed(a);break;case "img":if(this.filter(a))a:{if((c=a.src)&&!ud(c)){var d=new id(a.naturalWidth,a.naturalHeight),e=pd(a),f=jd(d)<jd(e)?d:e;if(f.width&&f.height){f=
Fd(a);c=new Y(f,c,d,e);break a}}c=null}break;default:if(this.filter(a)&&30>b.T){a:{c=V(a,"background-image");d=V(a,"background-repeat");e=V(a,"background-size");if(c&&("no-repeat"==d||"cover"==e)&&c&&5<=c.length&&"u"==c.charAt(0)&&"r"==c.charAt(1)&&"l"==c.charAt(2)&&"("==c.charAt(3)&&")"==c.charAt(c.length-1)&&(c=c.substr(4,c.length-5))&&!ud(c)&&(d=pd(a),d.width&&d.height)){for(var e=Fd(a),f=a.children,g=0;g<f.length;++g){var h=f[g];if("none"!=V(h,"display")&&jd(pd(h))>.1*jd(d)){e*=.1;break}}c=new Y(e,
c,void 0,d);break a}c=null}c&&++b.T}}if(!c)return null;e=c.h||c.g;if(c.a!=document.location.href&&(100>e.width||100>e.height))return null;d=c.c;d/=1+Math.exp(-1E-5*jd(e));e=e.width/e.height;1>e&&(e=1/e);2<e&&(d*=.8);e=c.a;this.g.href=e;e=this.g.href;f=decodeURIComponent(this.g.pathname||"");g=f.lastIndexOf(".");0<g&&(f=Bd[f.slice(g)])&&(d*=f);if(e in b.N&&b.N[e]>d)return null;b.N[e]=d;return new Y(d,e,c.g,c.h)};
var Dd=function(a,b,c,d,e,f){if(b.hasAttribute(d)&&b.getAttribute(d).toLowerCase()==e.toLowerCase()){d=b.getAttribute(f);if(!d||ud(d))return null;e=parseInt(b.getAttribute("data-google-stars-image-width"),10);f=parseInt(b.getAttribute("data-google-stars-image-height"),10);if(e&&f)return b=nd(b),a.g.href=b.documentURI,"/"!=a.g.pathname&&-1==b.body.innerHTML.indexOf(d)&&(c*=.5),new Y(c,d,new id(e,f))}return null},Ed=function(a){var b=a.getAttribute("itemprop");if(b&&"thumbnailurl"==b.toLowerCase()){b=
a.getAttribute("href")||a.getAttribute("content");if(!b||ud(b))return null;var c=parseInt(a.getAttribute("data-google-stars-image-width"),10);a=parseInt(a.getAttribute("data-google-stars-image-height"),10);if(c&&a)return new Y(.55,b,new id(c,a))}return null},Fd=function(a){var b=nd(a);if(a==b.documentElement)a=0;else{var c=b.body||b.documentElement,b=b.defaultView.pageYOffset||c.scrollTop;a=a.getBoundingClientRect().top+b}return 2E3<a?0:1/(1+Math.exp(.001*a))};
var Gd=function(a,b){Gd.w(this,"constructor",a);this.a=b};U(Gd,wd);var Hd=function(){Hd.w(this,"constructor")};U(Hd,W);Hd.prototype.a=function(a){var b=X(this,a.getElementsByTagName("meta"));b.push(Id(a));if(a=a.defaultView)a=a.getSelection().toString(),0<a.length&&b.push(new Gd(1,a));return b};
Hd.prototype.c=function(a){var b=0,c="";switch(a.tagName.toLowerCase()){case "meta":var d=a.getAttribute("name"),e=a.getAttribute("property");if(e&&"og:description"==e.toLowerCase())b=.9;else if(d)switch(d.toLowerCase()){case "twitter:description":b=.8;break;case "description":b=.7;break;case "msapplication-tooltip":b=.6}0<b&&(c=a.getAttribute("content")||"")}do a=c,c=td(c);while(c!=a);c=c.replace(/<[^<>]*?>/g,"");c=c.trim();return 5<c.length?(1024<c.length&&(c=c.substr(0,1021)+"..."),new Gd(b,c)):
null};
var Id=function(a){if(a.body){var b="",c="",d=0;a=a.body.innerText.replace(/(\r\n|\r)/g,"\n");for(var e=a.split("\n"),f=0;f<e.length;++f){for(var b=e[f].trim().replace(/\s+/g," "),g=b.split(" "),h=g.length,k,y=k=0;y<b.length;++y){var q=b.charAt(y);("a"<=q&&"z">=q||"A"<=q&&"Z">=q)&&++k}if(y=64<=b.length&&8<=h&&k>=.4*b.length){for(q=y=0;q<b.length;++q)/[^a-zA-Z0-9\r\n\t ]/.test(b.charAt(q))&&++y;y=0<y}if(y&&24>=Jd(g))break;k>=.4*b.length&&h>d&&24>=Jd(g)&&(c=b,d=h);b=""}0==b.length&&20<c.length&&4<= d&&(b=c);a=a.trim().replace(/[\t\n ]+/g," ");return new Gd(.1,b||a.substring(0,1024))}return null},Jd=function(a){for(var b=0,c=0;c<a.length;++c)b=Math.max(a[c].length,b);return b};
var Kd=function(a,b){Kd.w(this,"constructor",a);this.a=b};U(Kd,wd);var Ld=function(a){return a.a};var Md=function(a,b,c){Md.w(this,"constructor",a);this.g=b;this.a=c};U(Md,wd);var Nd=function(a,b,c,d){this.g=a;this.a=b;this.c=c;this.h=d};Nd.prototype.getTitle=function(){return this.g};var Od=function(){Od.w(this,"constructor")};U(Od,W);Od.prototype.a=function(a){var b=X(this,a.getElementsByTagName("meta")).concat(X(this,a.getElementsByTagName("title"))),c=X(this,a.getElementsByTagName("h1"));0<c.length?1==c.length&&(b=b.concat(c)):(c=X(this,a.getElementsByTagName("h2")),0<c.length?1==c.length&&(b=b.concat(c)):(c=X(this,a.getElementsByTagName("h3")),0<c.length&&1==c.length&&(b=b.concat(c))));a.title&&b.push(new Kd(1,a.title));b.push(new Kd(.1,a.documentURI));return b};
Od.prototype.c=function(a){var b=0,c="";switch(a.tagName.toLowerCase()){case "title":b=.5;c=sd(a);break;case "h1":b=.4;c=sd(a);break;case "h2":b=.3;c=sd(a);break;case "h3":b=.2;c=sd(a);break;case "meta":var d=a.getAttribute("name"),e=a.getAttribute("property");if(e&&"og:title"==e.toLowerCase())b=.9;else if(d)switch(d.toLowerCase()){case "application-name":b=.8;break;case "twitter:title":b=.7;break;case "title":b=.6}0<b&&(c=a.getAttribute("content")||"")}c=c.trim();do a=c,c=td(c);while(a!=c);return 1< c.length?new Kd(b,c):null};
var Pd=function(){Pd.w(this,"constructor")};U(Pd,W);Pd.prototype.c=function(a){switch(a.tagName.toLowerCase()){case "meta":var b;a:{if(a.hasAttribute("property")&&"og:video"==a.getAttribute("property").toLowerCase()){b=a.getAttribute("content");var c=parseInt(a.getAttribute("data-google-stars-video-width"),10);a=parseInt(a.getAttribute("data-google-stars-video-height"),10);if(b&&0<c&&0<a){b=new Md(1,b,new id(c,a));break a}}b=null}return b}return null};
var Qd=function(){this.g=new Od;this.c=new Hd;this.a=new Ad;this.h=new Pd};var Rd=function(){this.a=0;this.g=Promise.resolve();this.c=null},Ud=function(a){if(0==a.a){var b=document.getElementsByTagName("meta"),c=document.getElementsByTagName("link");a.a=b.length+c.length;if(0<a.a){a.g=new Promise(function(a){this.c=a}.bind(a));for(var d=0;d<b.length;d++)Sd(a,b[d]);for(d=0;d<c.length;d++)Td(a,c[d]);setTimeout(a.c,5E3)}else a.g=Promise.resolve()}return a.g},Sd=function(a,b){var c="";if(b.hasAttribute("property"))switch(b.getAttribute("property").toLowerCase()){case "og:image":var c=
b.getAttribute("content"),d=qd(b).children,e=Vd(d,"og:image:width"),d=Vd(d,"og:image:height");0<e&&0<d&&(b.setAttribute("data-google-stars-image-width",e),b.setAttribute("data-google-stars-image-height",d));break;case "og:video":d=qd(b).children,e=Vd(d,"og:video:width"),d=Vd(d,"og:video:height"),0<e&&0<d&&(b.setAttribute("data-google-stars-video-width",e),b.setAttribute("data-google-stars-video-height",d))}else if(b.hasAttribute("name"))switch(b.getAttribute("name").toLowerCase()){case "msapplication-tileimage":case "twitter:image":c=
b.getAttribute("content")}else if(b.hasAttribute("itemprop"))switch(b.getAttribute("itemprop").toLowerCase()){case "thumbnailurl":c=b.getAttribute("href")||b.getAttribute("content")}Wd(a,c,b)},Td=function(a,b){var c="";if(b.hasAttribute("rel"))switch(b.getAttribute("rel").toLowerCase()){case "apple-touch-icon-precomposed":case "apple-touch-icon":case "image_src":c=b.getAttribute("href")}else if(b.hasAttribute("itemprop"))switch(b.getAttribute("itemprop").toLowerCase()){case "thumbnailurl":c=b.getAttribute("href")||
b.getAttribute("content")}Wd(a,c,b)},Vd=function(a,b){for(var c=0;c<a.length;++c){var d=a[c];if(d.hasAttribute("property")&&d.getAttribute("property").toLowerCase()==b&&d.hasAttribute("content"))return d.getAttribute("content")}return""},Wd=function(a,b,c){!b||c.hasAttribute("data-google-stars-image-width")&&c.hasAttribute("data-google-stars-image-height")?0==--a.a&&a.c():Xd(a,b,a.h.bind(a,c))},Xd=function(a,b,c){var d=new Image,e=function(b){"load"==b.type&&c(d.naturalWidth,d.naturalHeight);0==--a.a&&
a.c();d.removeEventListener("load",e);d.removeEventListener("error",e)};d.addEventListener("load",e);d.addEventListener("error",e);d.src=b};Rd.prototype.h=function(a,b,c){a.setAttribute("data-google-stars-image-width",b);a.setAttribute("data-google-stars-image-height",c)};
var Yd=function(){hd.call(this);this.a=null;this.s=new Rd;this.i=null;this.o=new gd(this);ka(this,ja(la,this.o))};u(Yd,hd);var Zd=fc("image.collections.extension.ContentController");Yd.prototype.c=function(a){Yd.H.c.call(this,a);this.o.listen(chrome.runtime.onMessage,this.W)};
Yd.prototype.W=function(a,b,c){c({received:"true"});switch(a.type){case "collect_page":if(null===this.a){b=a.clipId;c=a.userId;a=new Ta;D(a,1,b);D(a,2,c);b=new Ya;F(b,1,a);a=t();D(b,7,a);D(b,8,a);this.a=new S(b);b=document.documentURI;/\.(jpg|jpeg|png|gif|bmp|svg|tiff)$/i.test(b)?fd(this.a,1):fd(this.a,2);a=new Ob;try{Kb(b)}catch(d){b=encodeURI(b)}try{Kb(b)}catch(e){b=""}D(a.a,3,b);b=this.a;b.i=a;F(b.a,6,a.a);Ud(this.s).then(r(this.D,this,!0))}else Zd&&Zd.log(Zb,"Clip is already being created",void 0);
break;case "get_salient_images":Ud(this.s).then(r(this.D,this,!1));break;default:Zd&&Zd.log(Yb,"Invalid message type: "+a.type,void 0)}};
Yd.prototype.D=function(a){this.i||(this.i=new Qd);var b,c=this.i,d=document,e=yd(c.g,d);b=yd(c.c,d);for(var f=c.a.a(d),c=yd(c.h,d),d=0,g={},h=0;h<f.length;h++)g[f[h].a]||(g[f[h].a]=!0,f[d++]=f[h]);f.length=d;b=new Nd(e,b,f,c);f=b.c;f.sort(xd||Da);e=[];d=null;for(c=0;c<f.length;c++){g=d=new Tc;h=f[c].a;g.c=null;try{var k=H(g.a);D(k,1,h);g.c=new O(x(Sa(H(g.a))))}catch(y){h=H(g.a),D(h,1,void 0),h=H(g.a),D(h,2,void 0),h=H(g.a),D(h,3,void 0)}g.c&&C(g.a,6)&&D(g.a,6,!1);var q=f[c].g;if(q){var g=d,h=q.width,
q=q.height,T=H(g.a);D(T,2,h);g=H(g.a);D(g,3,q)}e.unshift(d.l())}if(a){!dd(this.a)&&d&&(a=this.a,k=d,a.c=k,F(a.a,5,k.a),k=t(),D(a.a,8,k));a=R(this.a);!a.getTitle()&&b.getTitle()&&a.setTitle(Ld(b.getTitle()));!x(C(a.a,2))&&b.a&&D(a.a,2,b.a.a);if(k=b.h)fd(this.a,4),a=new Vc,D(a.a,1,k.g),b=k.a.height,D(a.a,2,k.a.width),D(a.a,3,b),k=this.a,k.o=a,F(k.a,10,a.a);chrome.runtime.sendMessage({type:"created_clip",clipData:this.a.l(),images:e});this.a=null}else chrome.runtime.sendMessage({type:"salient_images_found", images:e})};
var $d=function(){this.a=t()},ae=new $d;$d.prototype.set=function(a){this.a=a};$d.prototype.get=function(){return this.a};var be=function(a){this.h=a||"";this.i=ae};be.prototype.a=!0;be.prototype.c=!0;be.prototype.g=!1;var Z=function(a){return 10>a?"0"+a:String(a)},ce=function(a,b){var c=(a.g-b)/1E3,d=c.toFixed(3),e=0;if(1>c)e=2;else for(;100>c;)e++,c*=10;for(;0<e--;)d=" "+d;return d},de=function(a){be.call(this,a)};u(de,be);
var ee=function(){r(this.h,this);this.a=new de;this.a.c=!1;this.a.g=!1;this.c=this.a.a=!1;this.g="";this.i={}};
ee.prototype.h=function(a){if(!this.i[a.c]){var b;b=this.a;var c=[];c.push(b.h," ");if(b.c){var d=new Date(a.g);c.push("[",Z(d.getFullYear()-2E3)+Z(d.getMonth()+1)+Z(d.getDate())+" "+Z(d.getHours())+":"+Z(d.getMinutes())+":"+Z(d.getSeconds())+"."+Z(Math.floor(d.getMilliseconds()/10)),"] ")}c.push("[",ce(a,b.i.get()),"s] ");c.push("[",a.c,"] ");c.push(a.getMessage());b.g&&(d=a.a)&&c.push("\n",d instanceof Error?d.message:d.toString());b.a&&c.push("\n");b=c.join("");if(c=fe)switch(a.h){case Xb:ge(c, "info",b);break;case Yb:ge(c,"error",b);break;case Zb:ge(c,"warn",b);break;default:ge(c,"debug",b)}else this.g+=b}};var fe=m.console,ge=function(a,b,c){if(a[b])a[b](c);else a.log(c)};
var he=function(){Q.call(this);this.a=new Yd;ka(this,ja(la,this.a))};u(he,Q);aa(he);var ie=new ee;0!=ie.c&&(ec(),ie.c=!1);var je=fc("image.collections.extension.Content"),ke=he.M();je&&je.log($b,"Initializing extension content",void 0);ke.a.c(ke);window.full_script_injected=!0;

}catch(e){_DumpException(e)}
// Google Inc.
